/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import database.GerenciadorConexao;
import java.awt.Event;
import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.accessibility.AccessibleContext;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paulo
 */
public class Relatorios extends javax.swing.JFrame {

    public Connection con;
    public Statement st;
    public ResultSet resultado;
    PreparedStatement instrucaoSQL = null;
    private String data;
    private String datai;
    private String dataf;

    public Relatorios() {
        initComponents();

        try {
            
            //con = GerenciadorConexao.abrirConexao();
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/livraria", "root", "");
            st = (Statement) con.createStatement();
            //JOptionPane.showMessageDialog(null, "Conectou com o bd!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na conexão com o banco de dados!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lglData = new javax.swing.JLabel();
        bntPD = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiaria = new javax.swing.JTable();
        btnImprimir = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDiariaDet = new javax.swing.JTable();
        lblTD = new javax.swing.JLabel();
        jdcDia = new com.toedter.calendar.JDateChooser();
        lblTotalD = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblD = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        btnPP = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPeriodo = new javax.swing.JTable();
        btnImprimir2 = new javax.swing.JButton();
        btnFechar2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPeriodoDet = new javax.swing.JTable();
        lblTP = new javax.swing.JLabel();
        jdcPI = new com.toedter.calendar.JDateChooser();
        jdcPF = new com.toedter.calendar.JDateChooser();
        lblTotalP = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblM = new javax.swing.JLabel();
        btnPM = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMensal = new javax.swing.JTable();
        btnImprimir3 = new javax.swing.JButton();
        btnFechar3 = new javax.swing.JButton();
        cboMM = new javax.swing.JComboBox<>();
        cboMA = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblMensalDet = new javax.swing.JTable();
        lblTM = new javax.swing.JLabel();
        lblTotalM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lglData.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lglData.setText("Data:");

        bntPD.setText("Pesquisar");
        bntPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPDActionPerformed(evt);
            }
        });

        tblDiaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Cliente", "Valor total (R$)"
            }
        ));
        tblDiaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDiariaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDiaria);

        btnImprimir.setText("Imprimir");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        tblDiariaDet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Produto", "Descrição", "Quantidade", "Valor R$"
            }
        ));
        jScrollPane4.setViewportView(tblDiariaDet);

        lblTD.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblTD.setText("Total R$:");

        lblTotalD.setText("              R$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lglData)
                        .addGap(18, 18, 18)
                        .addComponent(jdcDia, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(bntPD, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalD, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFechar, btnImprimir});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntPD)
                            .addComponent(jdcDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lglData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTD)
                    .addComponent(lblTotalD))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnFechar, btnImprimir});

        jTabbedPane1.addTab("Relatório diário", jPanel2);

        lblD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblD.setText("De: ");

        lblA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblA.setText("Até:");

        btnPP.setText("Pesquisar");
        btnPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPPActionPerformed(evt);
            }
        });

        tblPeriodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Cliente", "Valor total (R$)"
            }
        ));
        tblPeriodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPeriodoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPeriodo);

        btnImprimir2.setText("Imprimir");

        btnFechar2.setText("Fechar");
        btnFechar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechar2ActionPerformed(evt);
            }
        });

        tblPeriodoDet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Produto", "Descrição", "Quantidade", "Valor R$"
            }
        ));
        jScrollPane5.setViewportView(tblPeriodoDet);

        lblTP.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblTP.setText("Total R$:");

        lblTotalP.setText("            R$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblTP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(btnImprimir2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar2)))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblD)
                    .addComponent(lblA))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdcPF, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jdcPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPP, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFechar2, btnImprimir2});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdcPI, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblA)
                            .addComponent(jdcPF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPP)
                        .addGap(27, 27, 27)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTP)
                    .addComponent(lblTotalP))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnFechar2, btnImprimir2});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jdcPF, jdcPI});

        jTabbedPane1.addTab("Relatório por período", jPanel3);

        lblM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblM.setText("Data:");

        btnPM.setText("Pesquisar");
        btnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMActionPerformed(evt);
            }
        });

        tblMensal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Cliente", "Valor total (R$)"
            }
        ));
        tblMensal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMensalMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMensal);

        btnImprimir3.setText("Imprimir");

        btnFechar3.setText("Fechar");
        btnFechar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechar3ActionPerformed(evt);
            }
        });

        cboMM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cboMA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021" }));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel1.setText("mês");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setText("ano");

        tblMensalDet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Produto", "Descrição", "Quantidade", "Valor R$"
            }
        ));
        jScrollPane6.setViewportView(tblMensalDet);

        lblTM.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblTM.setText("Total R$:");

        lblTotalM.setText("             R$");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalM, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(lblM)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboMM, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboMA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPM, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(btnImprimir3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFechar3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel1)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFechar3, btnImprimir3});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPM, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblM)
                        .addComponent(cboMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTM)
                    .addComponent(lblTotalM))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImprimir3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnFechar3, btnImprimir3});

        jTabbedPane1.addTab("Relatório mensal", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPDActionPerformed

        Date dia = jdcDia.getDate();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        this.data = formato.format(dia);
        
        try {
            DefaultTableModel tabela = (DefaultTableModel) tblDiaria.getModel();
            tabela = (DefaultTableModel) tblDiaria.getModel();
            tabela.setNumRows(0);
            String linhapesq = "select cliente.nome, livro.id, livro.titulo, livro.preco, venda.dt_compra from venda "
                    + "join livro on venda.id = livro.id "
                    + "join cliente on venda.cpf = cliente.cpf where dt_compra = '"
                    + data + "'";
            resultado = st.executeQuery(linhapesq);
            while (resultado.next()) {
                tabela.addRow(new Object[]{
                    resultado.getString("dt_compra"),
                    resultado.getString("nome"),
                    resultado.getString("preco")
                }
                );
            }
            
            double soma = 0;
            for(int i = 0; i < tblDiaria.getRowCount(); i++){
                double valor = Double.parseDouble((String) tblDiaria.getValueAt(i, 2));
                soma += valor;
            }
            lblTotalD.setText(String.valueOf(soma));            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bntPDActionPerformed

    private void btnPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPPActionPerformed

        Date inicio = jdcPI.getDate();
        Date fim = jdcPF.getDate();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        this.datai = formato.format(inicio);
        this.dataf = formato.format(fim);
        
        try {
            DefaultTableModel tabela = (DefaultTableModel) tblPeriodo.getModel();
            tabela = (DefaultTableModel) tblPeriodo.getModel();
            tabela.setNumRows(0);
            String linhapesq = "select cliente.nome, livro.id, livro.titulo, livro.preco, venda.dt_compra from venda "
                    + "join livro on venda.id = livro.id "
                    + "join cliente on venda.cpf = cliente.cpf where date(dt_compra) between '"
                    + datai + "' and '" + dataf + "' order by venda.dt_compra";
            resultado = st.executeQuery(linhapesq);
            while (resultado.next()) {
                tabela.addRow(new Object[]{
                    resultado.getString("dt_compra"),
                    resultado.getString("nome"),
                    resultado.getString("preco")
                }
                );
            }
            
            double soma = 0;
            for(int i = 0; i < tblPeriodo.getRowCount(); i++){
                double valor = Double.parseDouble((String) tblPeriodo.getValueAt(i, 2));
                soma += valor;
            }
            lblTotalP.setText(String.valueOf(soma));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnPPActionPerformed

    private void btnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMActionPerformed
             
        try {
            DefaultTableModel tabela = (DefaultTableModel) tblMensal.getModel();
            tabela = (DefaultTableModel) tblMensal.getModel();
            tabela.setNumRows(0);
            String linhapesq = "select cliente.nome, livro.id, livro.titulo, livro.preco, venda.dt_compra from venda "
                    + "join livro on venda.id = livro.id "
                    + "join cliente on venda.cpf = cliente.cpf where month(dt_compra) = "
                    + cboMM.getSelectedItem().toString() + " and year(dt_compra) = " 
                    + cboMA.getSelectedItem().toString() + " order by venda.dt_compra";
            resultado = st.executeQuery(linhapesq);
            while (resultado.next()) {
                tabela.addRow(new Object[]{
                    resultado.getString("dt_compra"),
                    resultado.getString("nome"),
                    resultado.getString("preco")
                }
                );
            }
                       
            double soma = 0;
            for(int i = 0; i < tblMensal.getRowCount(); i++){
                double valor = Double.parseDouble((String) tblMensal.getValueAt(i, 2));
                soma += valor;
            }
            lblTotalM.setText(String.valueOf(soma));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnPMActionPerformed

    private void btnFechar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechar2ActionPerformed

        System.exit(0);
    }//GEN-LAST:event_btnFechar2ActionPerformed

    private void btnFechar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechar3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnFechar3ActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void tblDiariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDiariaMouseClicked
        // TODO add your handling code here:
        
        String nome = (String) tblDiaria.getValueAt(tblDiaria.getSelectedRow(), tblDiaria.getSelectedColumn());
        
        try {
            DefaultTableModel tabela = (DefaultTableModel) tblDiariaDet.getModel();
            tabela = (DefaultTableModel) tblDiariaDet.getModel();
            tabela.setNumRows(0);
            String linhapesq = "select cliente.nome, livro.id, livro.titulo, livro.preco, venda.dt_compra from venda "
                    + "join livro on venda.id = livro.id "
                    + "join cliente on venda.cpf = cliente.cpf where nome = '"
                    + nome + "' and dt_compra = '" + data + "'";
            resultado = st.executeQuery(linhapesq);
            
            while (resultado.next()) {
                tabela.addRow(new Object[]{
                    resultado.getString("livro.id"),
                    resultado.getString("livro.titulo"),
                    resultado.getString("livro.titulo"),
                    resultado.getString("preco")
                }
                );
            }           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }        
    }//GEN-LAST:event_tblDiariaMouseClicked

    private void tblPeriodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeriodoMouseClicked
        // TODO add your handling code here:
        
        String nome = (String) tblPeriodo.getValueAt(tblPeriodo.getSelectedRow(), tblPeriodo.getSelectedColumn());
        
        try {
            DefaultTableModel tabela = (DefaultTableModel) tblPeriodo.getModel();
            tabela = (DefaultTableModel) tblPeriodoDet.getModel();
            tabela.setNumRows(0);
            String linhapesq = "select cliente.nome, livro.id, livro.titulo, livro.preco, venda.dt_compra from venda "
                    + "join livro on venda.id = livro.id "
                    + "join cliente on venda.cpf = cliente.cpf where date(dt_compra) between '"
                    + datai + "' and '" + dataf + "' and nome = '" + nome + "'";
            resultado = st.executeQuery(linhapesq);
            while (resultado.next()) {
                tabela.addRow(new Object[]{
                    resultado.getString("livro.id"),
                    resultado.getString("livro.titulo"),
                    resultado.getString("livro.titulo"),
                    resultado.getString("preco")
                }
                );
            }       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tblPeriodoMouseClicked

    private void tblMensalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMensalMouseClicked
        // TODO add your handling code here:
        
        String nome = (String) tblMensal.getValueAt(tblMensal.getSelectedRow(), tblMensal.getSelectedColumn());
        
        try {
            DefaultTableModel tabela = (DefaultTableModel) tblMensal.getModel();
            tabela = (DefaultTableModel) tblMensalDet.getModel();
            tabela.setNumRows(0);
            String linhapesq = "select cliente.nome, livro.id, livro.titulo, livro.preco, venda.dt_compra from venda "
                    + "join livro on venda.id = livro.id "
                    + "join cliente on venda.cpf = cliente.cpf where month(dt_compra) = '"
                    + cboMM.getSelectedItem().toString() + "' and year(dt_compra) = '" 
                    + cboMA.getSelectedItem().toString() + "' and nome = '"
                    + nome + "'";
            resultado = st.executeQuery(linhapesq);
            while (resultado.next()) {
                tabela.addRow(new Object[]{
                    resultado.getString("livro.id"),
                    resultado.getString("livro.titulo"),
                    resultado.getString("livro.titulo"),
                    resultado.getString("preco")
                }
                );
            }          
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tblMensalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPD;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFechar2;
    private javax.swing.JButton btnFechar3;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnImprimir2;
    private javax.swing.JButton btnImprimir3;
    private javax.swing.JButton btnPM;
    private javax.swing.JButton btnPP;
    private javax.swing.JComboBox<String> cboMA;
    private javax.swing.JComboBox<String> cboMM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdcDia;
    private com.toedter.calendar.JDateChooser jdcPF;
    private com.toedter.calendar.JDateChooser jdcPI;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblTD;
    private javax.swing.JLabel lblTM;
    private javax.swing.JLabel lblTP;
    private javax.swing.JLabel lblTotalD;
    private javax.swing.JLabel lblTotalM;
    private javax.swing.JLabel lblTotalP;
    private javax.swing.JLabel lglData;
    private javax.swing.JTable tblDiaria;
    private javax.swing.JTable tblDiariaDet;
    private javax.swing.JTable tblMensal;
    private javax.swing.JTable tblMensalDet;
    private javax.swing.JTable tblPeriodo;
    private javax.swing.JTable tblPeriodoDet;
    // End of variables declaration//GEN-END:variables
}
